# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./assets/github-contribution-grid-snake.svg
            ./assets/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push to GitHub
        if: ${{ github.event_name == 'schedule' && (github.run_number % 5 == 0 || github.run_number % 5 == 1 || github.run_number % 5 == 2) }}
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: 'Generate Contribution Snake'
